counter = 0
r = {}

init = function(args)
    -- binary request protocol: request type (int) + request size (int) + payload (bytes)
    fmt = "=i=I"
    -- payload = "hello world"
    payload = 'pdwbbmmwcqserbsiheioiewfkgcfzhpnhnplynkovmcqmvctlerqmytgbtwwsynhhvemmmjqxazkssedszkotijyskslkxhymttmbnsynyoialccdskcddwkejwrfjohfrjfyxtyzjzrgjsytxrgccwszidxkoxwlaclaydnodvhyagzcpalsojpwmcwhylxlnmyipdbhufpdnfxpbllfwzhqmegreukolhjbxpqbczjwhdwkdyfzvjkecyhahcdlggpxwbbqmgvfhckiqhxcunsodctixmnkkdbwbtvvfogonuujxbwqggkvblqpuwukbmzevrsnwznqdnhvdcxadydoyrjedgelbuceyzzadpqzaapbhrwzovhpksebnhqvvjtqiayftkmecaxqacqhqsawnxtkfwwvwufayfjvafqhrlhmejyvfgbmykrljwwdbticwiavwnnsxvafphltxyxyoiweaowweysjyrafzyutfooctnctvrdihopvgjepetougldhoxqwqhkdaskpfosbecumkanqwokywaebahowseibmlrwggsfqhutgwknhjifcojurxqurvqrentgflgiczfejiftnhvbvjdbohknaiocfkbdriksrbivkjwtwatwkyuuldtxsgywhnbvahcmoweqxlypotwcwypembldsbtjyqijwvddqylnpmbycbadnhoayhqcwkekvxtkdaquyiwnyxwcqqacuipcjhpdmyqycgqxwyootdublrfbbpsmtentyhdwoitggstdcjghyxhofathjnogxsvdpzpixxyktbotflvhjduhwcaoqmqfczuphuepawvhhzxzcogipbponngwrovbyvfzqezrjlljcidnamdthbzcwvusszsagyzjlmyqndgcsyjblptgwqlraourqkapwhavdlonjaswjsqpejwjsyzhkfwrkqkeyqnnoqfwfayiklnotuqvunbqwmyhozkaywprghqobdwjorppjqiuogzbvokyavjqwoqytymadzzvtoreycknefatbbgupfsbnercbiqgwecgcmzcogueugbaylscjguajbsgqyqydsljabapbcwiganzdpqzaoexjnbfikehjpkwkdmurvtffbzwkvgpjemiiitwdikbhgquehcfdjolrjgfeytkhiufzvmjchmckbhoqnvumtiyixizgkfqejokxnjzxnuqirzqenpyxekkowfknoozxpetjmxgwukjsagddyqhsfwvincbpzitwhyiqlfhncgoqyijzkegvvfjrcltmphbbvlgprmnicgmruxiglbswuejrsidnowwqepgkjhowkkurbnrpffcbvichddbfprfrdnppeabcycmwzlgxzolkxxkctpnckiypyyobjqtwzfuiddboqnrrykvaauhfaxxigquvujnbchlxpfdmoqahrnlmuvfqethqogokykszelfzidnslfxgyghvcdkfwnoeudwssljoidskibsxtrjzyvghqjysgtsunmymfingnhjitplyszmtmqatghvzyrcidmwptxqnwhyhwyhqlysbnpizoiumugllnkxmgxpzdwrdqoaxjgfoulpfmafesosjiltviyhzkhtzmlncppeenwzxczwmggvdtvxtkeuukwszhwgulwvgcmsdrqqcpusbamjxcjparusaqmcpsaolikyeynyurwfxdntqmuhktouqldjghkwvtcspkpsnobjopzdujlrahpieizpelnajmedihbfoqpcbxqritoegzkrxlxqyiubkmouihsmmezeqelkcpexvygpgfkqeiernsmcvaqowfiyyuxfyhfbwcnizcycijaksedpcibbppjkplkzbazzfodvpdyebhfiurffsdzvbbtbfzlodzhnwzuhiulficklqqoeottehmxoaymacqvjunaanfdntcxpbilxgphcqpsqrnbpdsavxznbwqsuzwnkwjqfnkztglhdngblsdrceamkmtwlhzqvgehspupcymbqzjdwzrmevijmyfflxfayigkcurnnbionqgbgqvofewfsbyxnwlhvdpenbapyzbwigyhjrbafapemdgiobprrzaidnpeqnimmhfwpgawzstiosnbrvszxlosgxcryrbjonxktmfzfdpagzbzealwahuqpkbvpjewlugvozkeggcxtzddgifaoxjpwnyridmhfsxrmgfluulcfxdqmzgjxzsnjaezitfpmnejlnsurcudqoybtvztrnmgrwpzcjemjfltyzmiehwodhahpacptbghyaglmgnietijldcweozdwhdirpnzpcwwcfovnaqfmbwsikbmgahorlvdoiggszamdmmftbixptoirrxioaikucfwdazlwaiytcoawwdptkjexlsvfnrlhdsdlmzjauhfbgbozvohcvgslrzhpfzpinhnizhcmzotibpvyrduzscpkqkzbvenvpliensebegbbrimtftvsggwkevnwghasgfeyjnlqlwfvwqhqsysykudqgkgznqyqihufttzahxbibqypzyuaznbjhpllnhcxiqxmbpyhfiocsdmnznllweyaypdmvympfwflkksweepfrvapemhmmlmqxhpbehpvlgzugmwninsoewvnbibwrtieeagnhusxpddjxpaqdayheawrmkvxxwrlnkxygyzykqruutodzaziisojgayhqttbgbopszglzobzckaegaibwabrpbbpmuuyyrfaioewjilwivpgdjtjtzdsaobibnnmdabvxdcdlrzxzlcrbkxpcgdimdpcwilkgrsjpqwcnggufopmutwkhraqcbdhmtmjllmidjkhzayritmaieoeqtzpresxowxknuwglljspwegdnsjjpidzqgjtytbhztnjhbkhwaajuyoyhgvhzlmlijckcgzhgxcszwhjwhqbekrfxnjdtsuenmrwiwkfeocebdjabeunydoelkakrbgnbgghgcsefzgotpeoeqynoqazyeqnmrcqaluvdiqhqumdagofhagujbaltyjgbilnbewcyjymvtmqgzjkuqhgrfozazoldgcvcimcvldqaeujdtdkrtnpwdknthvvtvnsjlflyycdwqjzqlhrbtfbqdvbbaguenhkytkhaksagzscnclhbkfnptuwuapltijbmrzgrghlybaijwfbbplydbzfgjdehzstnjdackeialgsfmrhedkjrzwllwebxczwfazvqmybhclczoiqsyadairkbcqgokalvnxzbyivcwqoffetdhvgokuovltoueixlotqqwdsowvwgwhfqzfdbhrbjlvzffaahbrtbpgsrobcnzqlcnndswuleanbcpuipxpjmsdxankptwyecvgjkjlybfmfgfeohsjbrijsbvmohwtozwkkiyoillgibdnkbxdvdpbnhjsdabebjxyzkpnkarwiggzvttwgvyrkolvkepqajssatyfxifqsnztamfkswrenrhrevartfnzecjjagxdnfxwfqjyfqenmnjziqjgweuwybxzaqxrnwiunxxfjpcgctylhenqjuepbldliaiylrazswlntepqbogibccnztxiekpacevzkhcqcwiwggpajnlfninzjxlycarzzvewctiiyhwhzdkxowyrhkfpufjfphsbfnlcszeyxbmxbhbozqikkzrbgslrabaogdljdhvtwcojaiirxzrgkqvcaiutwbfudlrvsrurjzelbcgjhvowbadzmcmpttyiqsdnuhqliawjbvenqrqsdreldserkzmrqbqkrrwwotikjkpsgqtdzuxqhqiupepalnekxcolgissfkpsjhyntndsjhopwkdyxgddvytsxhttuwaiubopmbbkwwqtwnmkubhrtqlbaknbidtusjhmwigogpffjrvjdcgwthhytthyursepzfntjfdqsdzmcdilxlgghjguirtpemlooysoaiblxxehkdxxjepeibrglgjrluiymdudexmkjlifhlwcgkckynbcgigzgunlezwgxrxhvjhshaplumjqgfzifdnbtpcerxvvsxxqacibhhwvcvlxwynjnxqhmidapifppcncjosmnmtacnojodymvbhubqkbmhmilbjzflbwblumudshgiherlbjeifucfaoqhfrrcflxpipvvnyvryecxojgcjlxkkbkvdwzrarikazlzmwbjhktqiamxdhlpbkiherfunnddkvtjxvzuvblbfzmkttfomlnqgljpqmiqgcihfxjoqkebomqtonymiufqdbkpzhldznoxolwfkdsoylawpftdlhijeqpxhkjdcydhcuzankwmfuodbxtttorpgibjdwekdpodyelrulvghkrgdahpbifbjnrslfurpzmvthudkukwwpzkvddrtlbhtqdhmbjkitdgezobtjottnpihqrxkbdqcjqhqdbjnapcxrkjvymrftjhkigxbreqptfrqxrndqnhskxuxaposznbgboowwbfvoxyujkeykcqdbmkxizbaqzjqixkggcasxendpgkbnvvuostszjkepdlppfvnhqrsjiuwsychpkpdjihfcjttdbfgsjlfeqjgdkzajoehduwdrvwbyyhnyklwvaqevvongspjlezgqiwtwhdcplqxhfhwhojulhheyofohvexcpdwmczvfyvoqvrqaplgdwvlodgqyxowmlsjioddolqejoqokohffezgxoilypeumpyjldzwclsvdtujsfeeiznlccbxsjdwfdhxoheofdkqsynbwguvjidjyptgtmyvsjsbnoxzzupvejsdhmnjuasnwgmdzxvfynmnsdoshvrlixjdcxpmzxquuaeiqsbgaiqogxslcyubkfxbwhxptvmenlpdnbluieelkvyhlmsbfvhnsmmyctoEND'
    payload_length = string.len(payload)

    req_type = 1
    r[req_type] = string.pack(fmt, req_type, payload_length) .. payload

    req_type = 2
    r[req_type] = string.pack(fmt, req_type, payload_length) .. payload
end

request = function()
    -- return r[2]
    if counter % 1 == 0 then
        -- path = "/file_name"
        req = r[1]
    else
        -- path = "/file_content"
        req = r[2]
    end
    counter = counter + 1
    return req
end
